### ISSUE TITLE
[Suggestion] Gamepad support

### ISSUE THREAD

**Issue by Maks7594** [GaryOderNichts/evwii#2]
### This might be impossible and I just don't know it, but I'm suggesting it anyway.

You can change the controls in the settings menu in the plugin configuration menu, like for example to act like a Classic Controller (Pro), or to act as a Wiimote with a Nunchuk (don't humiliate me i don't know how to say that), or just a normal Wiimote.

The controls would also have the function of mapping the same button to 2 different buttons (like binding A to both X and Y on the Gamepad).

I hope this is possible! :D

**Comment by GaryOderNichts** [comment]
That's out of scope for this project.
That would require heavy vIOS modifications while in vWii mode, similar to how HAI IOS applies patches to allow the Gamepad to work as a Classic Controller.
