### ISSUE TITLE
[Feature Request] Fix wii u powering down if gamepad is plugged into USB port while in vWii

### ISSUE THREAD

**Issue by qwertyuiopasd1113** [GaryOderNichts/evwii#3]
Wondering if this is possible
Basically if you use a wii u gamepad USB charger, and plug it into the console, it powers off in vWii mode

**Comment by GaryOderNichts** [comment]
That's the first time I ever heard about this heh.
I don't even know what would need to be patched for this? Probably something in IOS?
This requires some more investigating, but might be out of scope for evwii.

**Comment by Ingunar** [comment]
> Wondering if this is possible Basically if you use a wii u gamepad USB charger, and plug it into the console, it powers off in vWii mode

Is the WiiU USB gamepad charger even an official Nintendo accessory?

**Comment by Ingunar** [comment]
Ok, based on the info from Reddit and GBAtemp, it seem that unofficial cables are unstable when connected to the WiiU USBs in the Wii mode, and even causing the USB ports to short. Honestly, I think that this is a thing that evWii can not fix. 

https://www.reddit.com/r/wiiu/comments/15q1qc7/comment/jw1nc4a/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by GaryOderNichts** [comment]
Yeah, this doesn't seem like something that can be fixed by eVwii.
