### ISSUE TITLE
[Feature Request] Dissabling the Deflicker Filter vWii Wide

### ISSUE THREAD

**Issue by Jiga64** [GaryOderNichts/evwii#4]
I'm pretty sure the Wii U doesn't do this automatically, but it would be really nice if evWii could disable the Deflicker Filter entirely so that I don't have to use something like USB Loader GX.

**Comment by GaryOderNichts** [comment]
The Deflicker Filter is applied by the titles themselves. This would require individual title patches which is out of scope for evWii.
