### ISSUE TITLE
Request:Gamepad as an Classic Controller

### ISSUE THREAD

**Issue by GjGamesBr** [GaryOderNichts/evwii#5]
hi, i'm here to request Gamepad on vWii as Classic cuz is very hard to play games with supports classic but with wiimote, principally WiiWare and Virtual Console stuff

**Comment by Mii-U** [comment]
That would be really great to have system wide in vWii mode. Until then, you can inject WiiWare and virtual console into the Wii u menu with Wii u gamepad support as a classic controller using UWUVCI and then installing to the home menu

**Comment by GaryOderNichts** [comment]
This needs to be handled in the IOS used by the game and is out-of-scope for evWii.
