### ISSUE TITLE
[FEATURE REQUEST] Color Space toggle

### ISSUE THREAD

**Issue by Mii-U** [GaryOderNichts/evwii#6]
I am posting in a separate issue in case it got buried in the longer one.

According to NoobletCheese, the chroma bug seems to be coming from the a misalingment of the CbCr channels, and that it could be solved by outputting RGB instead of YCbCr.

Could a toggle for RGB/YCbCr be added to evWii? Hopefully then we could at least bypass the problem until a fix is created.

Original post: https://gbatemp.net/threads/fixing-vwii-mode.573265/post-9758960

**Comment by GaryOderNichts** [comment]
Please collect all video issues in the original issue (#1).
Everything related to this are only speculations, and nothing has been actually confirmed yet.
So this isn't as easy as adding a toggle.
