### ISSUE TITLE
Restore settings when uninstalling

### ISSUE THREAD

**Issue by JalilCejin** [GaryOderNichts/evwii#9]
Hello.

Will uninstall restore the default settings?

Is there a procedure to do this correctly?

Thanks

**Comment by GaryOderNichts** [comment]
All patches applied by evWii are only temporary. Removing the plugin or not booting into the aroma environment will get rid of any applied patches.
If you want to restore the default settings of the plugin itself, delete the `wiiu/environments/aroma/plugins/config/evWii.json` file from your SD Card or select the default option from the config menu.
